# Modelos de Classificação
- Em modelos de classificação estamos tentando prever o valor de uma categoria (banana ou maçã, fraude ou não, 0 ou 1, etc)
- Podemos usar algoritmos como o Árvore de Classificação, KNN, SVM, ...
- Vamos usar novamente a base do titanic disponível em:
    - Base: `../../data/databaseTitanic.csv`

In [1]:
# Importando o pandas
import pandas as pd

In [2]:
# Importando a base
base = pd.read_csv('../../data/databaseTitanic.csv')

In [3]:
# Verificando as informações da base
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

**Podemos começar o tratamento retirando a coluna "Cabin" que tem muitos valores vazios**

In [4]:
# Eliminando a coluna 'Cabin'
base = base.drop('Cabin',axis=1)

In [5]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

**E então retirar todos os valores vazios**
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

In [6]:
# Eliminando valores vazios
base=base.dropna()

In [7]:
base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Name         712 non-null    object
 4   Sex          712 non-null    object
 5   Age          712 non-null    float64
 6   SibSp        712 non-null    int64
 7   Parch        712 non-null    int64
 8   Ticket       712 non-null    object
 9   Fare         712 non-null    float64
 10  Embarked     712 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 66.8+ KB

**E também retirar as colunas que não são valores inteiros**

In [8]:
# Selecionando as colunas com o tipo "object"
colunas = base.dtypes[base.dtypes.values == 'object'].index

In [9]:
# Eliminando essas colunas
base = base.drop(colunas,axis=1)

In [10]:
# Verificando novamente as informações da base
base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Age          712 non-null    float64
 4   SibSp        712 non-null    int64
 5   Parch        712 non-null    int64
 6   Fare         712 non-null    float64
dtypes: float64(2), int64(5)
memory usage: 44.5 KB

# O Scikit-Learn
- Ferramentas simples e eficientes para análise preditiva de dados
- Acessível a todos e reutilizável em vários contextos
- Construído em NumPy, SciPy e Matplotlib
- Disponível em: https://scikit-learn.org/

In [11]:
base.head(5)

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0            1         0       3  22.0      1      0   7.2500
1            2         1       1  38.0      1      0  71.2833
2            3         1       3  26.0      0      0   7.9250
3            4         1       1  35.0      1      0  53.1000
4            5         0       3  35.0      0      0   8.0500

In [12]:
# Definindo o X e y para o treino
X = base.drop("Survived", axis=1)
y = base.Survived

### Utilizando o KNN
- https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier

In [13]:
# Importando o KNN
from sklearn.neighbors import KNeighborsClassifier

In [14]:
# Criando o nosso classificador
neigh = KNeighborsClassifier(n_neighbors=3)

In [15]:
# Fazendo o fit com os dados
neigh.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [16]:
# Avaliando o modelo
neigh.score(X,y)

0.7907303370786517

### Utilizando a Árvore de Decisão
- https://scikit-learn.org/stable/modules/tree.html#classification

In [17]:
# Importando a árvore de decisão
from sklearn import tree

In [18]:
# Criando o nosso classificador
clfArvore = tree.DecisionTreeClassifier()

In [19]:
# Fazendo o fit com os dados
clfArvore = clfArvore.fit(X, y)

In [20]:
# Avaliando o modelo
clfArvore.score(X,y)

1.0

### Utilizando a Regressão Logística
- https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression

In [21]:
# Importando a regressão logística
from sklearn.linear_model import LogisticRegression

In [22]:
# Criando o nosso classificador e fazendo o fit com os dados
clfLog = LogisticRegression(random_state=0, max_iter=1000).fit(X, y)

In [23]:
# Avaliando o modelo
clfLog.score(X,y)

0.7064606741573034

### Avaliando modelos de classificação
- https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics
- Para isso, vamos usar os dados de teste
    - Base: `../../data/databaseTitanicTest.csv`

In [24]:
# Importando e visualizando a base de teste
teste = pd.read_csv('../../data/databaseTitanicTest.csv')

In [25]:
# Fazendo os mesmos tratamentos
teste = teste.drop('Cabin',axis=1)
teste = teste.dropna()
teste = teste.drop(colunas,axis=1)

In [26]:
# Verificando as informações da base
teste.head(5)

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0          892         0       3  34.5      0      0   7.8292
1          893         1       3  47.0      1      0   7.0000
2          894         0       2  62.0      0      0   9.6875
3          895         0       3  27.0      0      0   8.6625
4          896         1       3  22.0      1      1  12.2875

In [27]:
teste.info()

<class 'pandas.core.frame.DataFrame'>
Index: 331 entries, 0 to 415
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  331 non-null    int64
 1   Survived     331 non-null    int64
 2   Pclass       331 non-null    int64
 3   Age          331 non-null    float64
 4   SibSp        331 non-null    int64
 5   Parch        331 non-null    int64
 6   Fare         331 non-null    float64
dtypes: float64(2), int64(5)
memory usage: 20.7 KB

In [28]:
# Separando X e y da base
X_teste = teste.drop('Survived',axis=1)
y_teste = teste.Survived

In [29]:
# Fazendo a predicão com o KNN
pred_KNN = neigh.predict(X_teste)

In [30]:
# Predict com a Árvore de Decisão
pred_Arvore = clfArvore.predict(X_teste)

In [31]:
# Predict com Regressão Logística
pred_Log = clfLog.predict(X_teste)

**Matriz de confusão**
- https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html#sklearn.metrics.confusion_matrix

![img1-2.png](attachment:img1-2.png)

In [32]:
# Importando a matriz de confusão
from sklearn.metrics import confusion_matrix

In [33]:
# Verificando a matriz para o KNN
confusion_matrix(y_teste, pred_KNN)

array([[ 68, 136],
       [ 35,  92]])

In [34]:
# Para a Árvore de Decisão
confusion_matrix(y_teste, pred_Arvore)

array([[118,  86],
       [ 46,  81]])

In [35]:
# E para a Regressão Logística
confusion_matrix(y_teste, pred_Log)

array([[131,  73],
       [ 64,  63]])

**Acurácia**
- https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score

In [36]:
# Importando a métrica de acurácia
from sklearn.metrics import accuracy_score

In [37]:
# Verificando a acurácia para o KNN
accuracy_score(y_teste, pred_KNN)

0.48338368580060426

In [38]:
# Para a Árvore de Decisão
accuracy_score(y_teste, pred_Arvore)

0.6012084592145015

In [39]:
# E para a Regressão Logística
accuracy_score(y_teste, pred_Log)

0.5861027190332326

**Precisão**
- https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html#sklearn.metrics.precision_score

In [40]:
# Importando o precision_score
from sklearn.metrics import precision_score

In [41]:
# Verificando a precisâo para o KNN
precision_score(y_teste, pred_KNN)

0.40350877192982454

In [42]:
# Para a Árvore de Decisão
precision_score(y_teste, pred_Arvore)

0.48502994011976047

In [43]:
# E para a Regressão Logística
precision_score(y_teste, pred_Log)

0.4632352941176471

**Recall**
- https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.html#sklearn.metrics.recall_score

In [44]:
# Importando o recall_score
from sklearn.metrics import recall_score

In [45]:
# Verificando o recall para o KNN
recall_score(y_teste, pred_KNN)

0.7244094488188977

In [46]:
# Para a Árvore de Decisão
recall_score(y_teste, pred_Arvore)

0.6377952755905512

In [47]:
# E para a Regressão Logística
recall_score(y_teste, pred_Log)

0.49606299212598426